# coding=utf-8
u"""
    单元测试unittest 生成HTML报告测试

运行命令:
cd /home/scfan/pro/server && python -m  pro.tests.test_unittest_htmlreport

"""
 
import unittest
from ..tools.tools_unittest_HTMLTestRunner import HTMLTestRunner
from ..tools.tools_mathfunc import *

class TestMathFunc(unittest.TestCase):
 
    def test_add(self):
        self.assertEqual(3, add(1, 2))
        self.assertNotEqual(3, add(2, 2))
 
    def test_minus(self):
        self.assertEqual(1, minus(3, 2))
 
    def test_multi(self):
        self.assertEqual(6, multi(3, 2))
 
    def test_divide(self):
        self.assertEqual(2, divide(6, 3))
        self.assertEqual(2.5, divide(5, 2))

 
if __name__ == '__main__':
    suite = unittest.TestSuite()
 
    tests = [TestMathFunc("test_add"), TestMathFunc("test_minus"), TestMathFunc("test_divide")]
    suite.addTests(tests)

    with open('HTMLReport.html', 'w') as f:
        runner = HTMLTestRunner(stream=f,
                                title = 'MathFunc Test Report',
                                description='generated by HTMLTestRunner.',
                                verbosity=2
                                )
        runner.run(suite)



